spring.application.name=brinquedoteca-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/brinquedoteca
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=none

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/migration/V1__create_tables.sql

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
